# Generated by Django 3.1.1 on 2020-09-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BreastCancerApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotes',
            name='author',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
