# Generated by Django 3.1.1 on 2020-09-29 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BreastCancerApp', '0003_auto_20200929_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
